### ISSUE TITLE
New social icon for OK.ru

### ISSUE THREAD

**Issue by spotman** [BenSibley/Mission#2]
Hello, @BenSibley !

Thanks for this great WP theme!
May I ask you to add a new icon for OK.ru social network? It is used widely in Russia. There is an icon in the FontAwesome which you may use as a reference http://fontawesome.io/icon/odnoklassniki/

**Comment by BenSibley** [comment]
Thanks!

I'll add that one in the next update.

**Comment by spotman** [comment]
Thanks for your support, @BenSibley !

**Comment by BenSibley** [comment]
Just added this icon to the new update. You can find it in the Social Media Icons section listed under the VK icon.

**Comment by spotman** [comment]
Thanks, @BenSibley ! It just works :)
